name: Publish Nuget
on:
  push:
   tags:        
      - '**'

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
        
      - name: List installed .NET info
        shell: pwsh
        run: dotnet --info

      - name: Deploy
        run: |
          tagParts=(${GITHUB_REF//\// })
          VERSION="${tagParts[2]}"
          VERSION="${VERSION//v}"
          nuget restore
          cd sdk/Notifo.SDK/
          msbuild Notifo.SDK.Core.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release /p:Version=$VERSION
          dotnet nuget push bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
          cd ../Notifo.SDK.FirebasePlugin/
          msbuild Notifo.SDK.FirebasePlugin.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release /p:Version=$VERSION
          dotnet nuget push bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
          cd ../Notifo.SDK.Notifo.SDK.Worker/
          msbuild Notifo.SDK.Worker.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release /p:Version=$VERSION
          dotnet nuget push bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
          
          
          

