name: Publish Nuget
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: build test
        if: github.event_name == 'pull_request'
        run: |
          nuget restore
          cd sdk/Notifo.SDK.Core/
          mono '/Applications/Visual\ Studio.app/Contents/MonoBundle/MSBuild/Current/bin/MSBuild.dll' Notifo.SDK.Core.csproj
          cd ../Notifo.SDK.FirebasePlugin/
          mono '/Applications/Visual\ Studio.app/Contents/MonoBundle/MSBuild/Current/bin/MSBuild.dll' Notifo.SDK.FirebasePlugin.csproj
          cd ../Notifo.SDK.Worker/
          mono '/Applications/Visual\ Studio.app/Contents/MonoBundle/MSBuild/Current/bin/MSBuild.dll' Notifo.SDK.Worker.csproj

      - name: publish
        if: github.event_name != 'pull_request'
        run: |
          nuget restore
          cd sdk/Notifo.SDK.Core/
          msbuild Notifo.SDK.Core.csproj /p:Configuration=Release
          dotnet nuget push bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate -n
          cd ../Notifo.SDK.FirebasePlugin/
          msbuild Notifo.SDK.FirebasePlugin.csproj /p:Configuration=Release
          dotnet nuget push bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate -n
          cd ../Notifo.SDK.Worker/
          msbuild Notifo.SDK.Worker.csproj /p:Configuration=Release
          dotnet nuget push bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate -n
          
          
          

