name: Publish Nuget
on:
  push:
   tags:        
      - '**'

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          tagParts=(${GITHUB_REF//\// })
          VERSION="${tagParts[2]}"
          VERSION="${VERSION//v}"
          nuget restore
          cd sdk/Notifo.SDK/
          msbuild Notifo.SDK.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release /p:Version=$VERSION
          cd ../Notifo.SDK.FirebasePlugin/
          msbuild Notifo.SDK.FirebasePlugin.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release /p:Version=$VERSION
      - name: Publish NuGet
        run: |
          dotnet nuget push sdk/Notifo.SDK/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
          dotnet nuget push sdk/Notifo.SDK.FirebasePlugin/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
          

