name: Publish Nuget
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: build test
        if: github.event_name != 'push' || !contains(github.ref, 'refs/tags/')
        run: |
          nuget restore
          msbuild sdk/Notifo.SDK/Notifo.SDK.Core.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
          msbuild sdk/Notifo.SDK.FirebasePlugin/Notifo.SDK.FirebasePlugin.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
          msbuild sdk/Notifo.SDK.Worker/Notifo.SDK.Worker.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release

      - name: build release
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        run: |
          tagParts=(${GITHUB_REF//\// })
          VERSION="${tagParts[2]}"
          VERSION="${VERSION//v}"
          nuget restore
          msbuild sdk/Notifo.SDK/Notifo.SDK.Core.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release /p:Version=$VERSION
          msbuild sdk/Notifo.SDK.FirebasePlugin/Notifo.SDK.FirebasePlugin.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release /p:Version=$VERSION
          msbuild sdk/Notifo.SDK.Worker/Notifo.SDK.Worker.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release /p:Version=$VERSION

      - name: publish
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        run: |
          dotnet nuget push bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate#
          
          
          

