name: Publish Nuget

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set default Xamarin SDK versions
        run: |
          $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --ios=14.10

      - name: Setup .NET Core SDK 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Deploy
        run: |
          tagParts=(${GITHUB_REF//\// })
          VERSION="${tagParts[2]}"
          VERSION="${VERSION//v}"
          nuget restore
          cd sdk/Notifo.SDK/
          msbuild Notifo.SDK.Core.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release /p:Version=$VERSION
          dotnet nuget push bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
          cd ../Notifo.SDK.FirebasePlugin/
          msbuild Notifo.SDK.FirebasePlugin.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release /p:Version=$VERSION
          dotnet nuget push bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
          cd ../Notifo.SDK.Notifo.SDK.Worker/
          msbuild Notifo.SDK.Worker.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release /p:Version=$VERSION
          dotnet nuget push bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
          
          
          

